In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import requests
from api_keys import api_key
from datetime import datetime
from time import mktime

#need to fix
key ="54445e5623750bd7435f05cf140903c3"

ModuleNotFoundError: No module named 'api_keys'

In [3]:
#read data 
LR_csv = pd.read_csv("cleaned_data.csv")
LR_csv

,MONTH,SUPPLIER,FACTORY,COUNTRY,DPN,LOB,WATT_LEVEL,LR,CONSUMPTION,VID,CND,PID
0,JA,A,Brasilia,Brazil,7FHHV,Consumer,Medium,0,35,0,0,0
1,JA,A,Brasilia,Brazil,7FHHV,Consumer,Medium,0,50,0,0,0
2,JA,A,Brasilia,Brazil,7FHHV,Commercial,Medium,0,158,0,0,0
3,JA,A,Chengdu,China,7FHHV,Consumer,Medium,0,1,0,0,0
4,JA,A,Chengdu,China,7FHHV,Commercial,Medium,0,1,0,0,0
5,JA,A,Chengdu,China,FW8KR,Consumer,Low,0,3801,0,0,0
6,JA,A,Chengdu,China,FW8KR,Consumer,Low,0,3999,0,0,0
7,JA,A,Chengdu,China,FW8KR,Consumer,Low,0,5048,0,0,0
8,JA,A,Chengdu,China,FW8KR,Consumer,Low,0,1196,0,0,0
9,JA,A,Chengdu,China,FW8KR,Consumer,Low,0,764,0,0,0
10,JA,A,Chengdu,China,FW8KR,Consumer,Low,0,27,0,0,0
11,JA,A,Chengdu,China,FW8KR,Consumer,Low,0,299,0,0,0
12,JA,A,Chengdu,China,FW8KR,Consumer,Low,0,5,0,0,0
13,JA,A,Chengdu,China,FW8KR,Commercial,Low,0,83,0,0,0
14,JA,A,Chengdu,China,FW8KR,Commercial,Low,0,980,0,0,0
15,JA,A,Chengdu,China,FW8KR,Commercial,Low,0,64,0,0,0
16,JA,A,Chengdu,China,FW8KR,Commercial,Low,0,464,0,0,0
17,JA,A,Chengdu,China,FW8KR,Consumer,Low,0,289,0,0,0
18,JA,A,Kunshan,China,9W9MX,Commercial,Low,0,20,0,0,0
19,JA,A,Kunshan,China,9W9MX,Commercial,Low,0,729,0,0,0
20,JA,A,Kunshan,China,9W9MX,Commercial,Low,0,17,0,0,0
21,JA,A,Kunshan,China,9W9MX,Commercial,Low,0,752,0,0,0
22,JA,A,Kunshan,China,9W9MX,Commercial,Low,0,13,0,0,0
23,JA,A,Kunshan,China,9W9MX,Commercial,Low,0,668,0,0,0
24,JA,A,Kunshan,China,CP6DF,Consumer,Medium,0,31,0,0,0
25,JA,A,Kunshan,China,CP6DF,Consumer,Medium,0,3,0,0,0
26,JA,A,Kunshan,China,CP6DF,Consumer,Medium,0,192,0,0,0
27,JA,A,Kunshan,China,CP6DF,Consumer,Medium,0,307,0,0,0
28,JA,A,Kunshan,China,DJWGP,Commercial,Medium,0,1,0,0,0
29,JA,A,Kunshan,China,DJWGP,Commercial,Medium,0,21,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
14092,MY,E,Chengdu,China,VM732,Consumer,Low,0,1442,0,0,0
14093,MY,E,Chengdu,China,VM732,Consumer,Low,0,1099,0,0,0
14094,MY,E,Chengdu,China,VM732,Consumer,Low,0,1574,0,0,0
14095,MY,E,Chengdu,China,VM732,Consumer,Low,1,1,0,1,0
14096,MY,E,Chengdu,China,VM732,Consumer,Low,1,2956,0,1,0
14097,MY,E,Chengdu,China,VM732,Consumer,Low,0,2384,0,0,0
14098,MY,E,Chengdu,China,VM732,Consumer,Low,0,129,0,0,0
14099,MY,E,Chengdu,China,VM732,Consumer,Low,0,147,0,0,0
14100,MY,E,Chengdu,China,VM732,Consumer,Low,0,236,0,0,0
14101,MY,E,Chengdu,China,VM732,Commercial,Low,0,32,0,0,0
14102,MY,E,Chengdu,China,VM732,Consumer,Low,0,508,0,0,0
14103,MY,E,Chengdu,China,VM732,Consumer,Low,0,1092,0,0,0
14104,MY,E,Chengdu,China,Y3F7Y,Consumer,Low,0,9,0,0,0
14105,MY,E,Chengdu,China,Y3F7Y,Consumer,Low,0,26,0,0,0
14106,MY,E,Chengdu,China,Y3F7Y,Consumer,Low,0,54,0,0,0
14107,MY,E,Chengdu,China,Y3F7Y,Consumer,Low,0,706,0,0,0
14108,MY,E,Chengdu,China,Y3F7Y,Consumer,Low,0,16,0,0,0
14109,MY,E,Chengdu,China,Y3F7Y,Consumer,Low,0,2,0,0,0
14110,MY,E,Chengdu,China,Y3F7Y,Consumer,Low,0,831,0,0,0
14111,MY,E,Chengdu,China,Y3F7Y,Consumer,Low,0,217,0,0,0
14112,MY,E,Chengdu,China,Y3F7Y,Commercial,Low,0,106,0,0,0
14113,MY,E,Chengdu,China,Y3F7Y,Commercial,Low,0,796,0,0,0
14114,MY,E,Chengdu,China,Y3F7Y,Commercial,Low,0,181,0,0,0
14115,MY,E,Chengdu,China,Y3F7Y,Commercial,Low,0,2732,0,0,0
14116,MY,E,Chengdu,China,Y3F7Y,Commercial,Low,0,803,0,0,0
14117,MY,E,Chengdu,China,Y3F7Y,Commercial,Low,0,1347,0,0,0
14118,MY,E,Chengdu,China,Y3F7Y,Commercial,Low,0,140,0,0,0
14119,MY,E,Chengdu,China,Y3F7Y,Commercial,Low,1,3818,0,1,0
14120,MY,E,Chengdu,China,YWD3C,Commercial,Low,0,64,0,0,0
14121,MY,E,Chengdu,China,YWD3C,Commercial,Low,0,478,0,0,0

In [3]:
# making list for months and cities
cities = []
months = []
mons = []
for city in LR_csv["FACTORY"]:
    cities.append(city)
#gathering months and converting to numbers in the list    
for month in LR_csv["MONTH"]:
    mons.append(month)
    if month == "JA":
        months.append(1)
    if month == "FE":
        months.append(2)
    if month == "MR":
        months.append(3)
    if month == "AP":
        months.append(4)
    if month == "MY":
        months.append(5)

cities = list(dict.fromkeys(cities))
months = list(dict.fromkeys(months))
mons = list(dict.fromkeys(mons))
cities

['Brasilia', 'Chengdu', 'Kunshan', 'Penang', 'Mumbai', 'Suzhou', 'Taoyuan']

In [4]:
# getting long and lat
lat = []
lng = []
for city in cities:
    url = f"http://api.openweathermap.org/data/2.5/weather?q={city}&units=imperial&APPID={api_key}"
    url = requests.get(url).json()   
    lat.append(url["coord"]["lat"])
    lng.append(url["coord"]["lon"])

In [5]:
#creating new data frame with cities with lat and long (for easier discorvery)
city_coord_df = pd.DataFrame({"City":cities,"Latitude":lat,"Longitude":lng})
city_coord_df

       City  Latitude  Longitude
0  Brasilia    -10.90     -37.55
1   Chengdu     30.68     104.06
2   Kunshan     31.39     120.95
3    Penang     -7.81     113.99
4    Mumbai     19.01      72.85
5    Suzhou     31.30     120.58
6   Taoyuan     24.99     121.30

In [6]:
#converting to unix timestamp

t = datetime(2018, 1, 1)
unix_secs = mktime(t.timetuple())
dt = str(int(unix_secs))

#checking it worked
dt = 1559278800
date = datetime.utcfromtimestamp(int(dt)).strftime('%Y-%m-%d')

print(dt, date)

1559278800 2019-05-31

In [7]:
dts = []
i = 1
j = 1
for i in months:
    dts.append((2019, i, 1))
    if i == 1:
        j += 30
        dts.append((2019, i, j))
        j = 1
    if i == 2:
        j += 27
        dts.append((2019, i , j))
        j = 1
    if i == 3:
        j += 30
        dts.append((2019, i, j))
        j = 1
    if i == 4:
        j += 29
        dts.append((2019, i, j))
        j = 1
    if i == 5:
        j += 30
        dts.append((2019, i, j))
len(dts)

10

In [8]:
#making list of the start and then end of each months dt
unix_dts = []
x = 0
for x in range(len(dts)): 
    t = datetime(dts[x][0],dts[x][1],dts[x][2])
    unix_dt = mktime(t.timetuple())
    unix_dt = str(int(unix_dt))
    unix_dts.append(unix_dt)
unix_dts[0]

'1546322400'

In [11]:
#variables for the upcoming dataframe
temps = ['a','b','c','d','e','f','g']
col_names = ["JAstrt","JAend","FEstrt","FEend","MRstrt","MRend","APstrt","APend","MYstrt","MYend"]
i = 0
j = 0

temp_df = pd.DataFrame()
#nameing columns for temps
for mon in mons:
    count = 0
    for i in range(len(unix_dts)):

        if count%2 == 0:
            col = mon + "strt"
            city_coord_df[col] = temps
            count +=1
        else:
            col = mon + "end"
            city_coord_df[col] = temps
            count += 1
            
#pulling temp from unix dts            
for i in range(0,len(unix_dts)):
    d = unix_dts[i]
    temps = []

    
    for j in range(0,len(city_coord_df["City"])):
        lt = city_coord_df["Latitude"][j]
        lg = city_coord_df["Longitude"][j]
        drk_sky = f"https://api.darksky.net/forecast/54445e5623750bd7435f05cf140903c3/{lt},{lg},{d}?exclude=flags,hourly,minutely,alerts"
        drk_sky = requests.get(drk_sky).json()
        temps.append(drk_sky["daily"]["data"][0]["temperatureHigh"])
    col = col_names[i]
    city_coord_df[col] = temps
        

city_coord_df

,City,Latitude,Longitude,JAstrt,JAend,FEstrt,FEend,MRstrt,MRend,APstrt,APend,MYstrt,MYend
0,Brasilia,-10.90,-37.55,91.48,88.04,89.99,92.90,90.81,81.07,87.49,92.52,86.00,86.43
1,Chengdu,30.68,104.06,44.89,47.61,54.19,52.94,48.59,69.13,62.66,81.41,76.00,83.97
2,Kunshan,31.39,120.95,39.90,41.95,40.18,51.35,51.80,59.39,68.08,62.72,74.99,80.47
3,Penang,-7.81,113.99,88.70,89.01,88.04,92.13,88.33,89.84,87.67,85.57,86.32,91.94
4,Mumbai,19.01,72.85,87.07,83.56,81.52,83.60,84.12,86.96,87.42,91.25,90.23,91.17
5,Suzhou,31.30,120.58,42.78,45.18,44.57,54.12,53.21,61.70,66.42,70.44,76.11,81.00
6,Taoyuan,24.99,121.30,63.69,80.75,58.05,67.52,73.62,71.69,61.58,89.14,68.62,90.42

In [13]:
city_coord_df = city_coord_df[["City","Latitude","Longitude","JAstrt","JAend","FEstrt","FEend","MRstrt",
                               "MRend","APstrt","APend","MYstrt","MYend"]]
city_coord_df.to_csv("city_weather.csv")

In [14]:
city_coord_df

,City,Latitude,Longitude,JAstrt,JAend,FEstrt,FEend,MRstrt,MRend,APstrt,APend,MYstrt,MYend
0,Brasilia,-10.90,-37.55,91.48,88.04,89.99,92.90,90.81,81.07,87.49,92.52,86.00,86.43
1,Chengdu,30.68,104.06,44.89,47.61,54.19,52.94,48.59,69.13,62.66,81.41,76.00,83.97
2,Kunshan,31.39,120.95,39.90,41.95,40.18,51.35,51.80,59.39,68.08,62.72,74.99,80.47
3,Penang,-7.81,113.99,88.70,89.01,88.04,92.13,88.33,89.84,87.67,85.57,86.32,91.94
4,Mumbai,19.01,72.85,87.07,83.56,81.52,83.60,84.12,86.96,87.42,91.25,90.23,91.17
5,Suzhou,31.30,120.58,42.78,45.18,44.57,54.12,53.21,61.70,66.42,70.44,76.11,81.00
6,Taoyuan,24.99,121.30,63.69,80.75,58.05,67.52,73.62,71.69,61.58,89.14,68.62,90.42